<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5"/>
        <meta name="author" content="Vicky Noci - David Carrascal - Mohamed Malki"/>
        <link rel="shortcut icon" href="https://raw.githubusercontent.com/davidcawork/Pi-Home/main/img/icons/icon.jpg"/>
        <title>SEDA - eMet</title>
        <link  rel="stylesheet"  href="http://cdn.jsdelivr.net/gh/davidcawork/Pi-Home/css/app.css"  crossorigin="anonymous"/>
    </head>
    <body style="overflow: auto;">
        <div class="wrapper">
            <nav id="sidebar" class="sidebar">
                <div class="sidebar-content js-simplebar">
                    <a class="sidebar-brand" href="index.html">
                        <span class="align-middle">SEDA - eMet</span>
                    </a>
                    <ul class="sidebar-nav">
                        <li class="sidebar-header">Páginas</li>
                        <li class="sidebar-item active">
                            <a class="sidebar-link" href="index.html">
                                <i class="align-middle" data-feather="bar-chart-2"></i>
                                <span class="align-middle">Panel de control</span>
                            </a>
                        </li>
                        <div class="sidebar-cta">
                            <div class="sidebar-cta-content">
                                <strong class="d-inline-block mb-2">Estación meteorológica</strong>
                                <div class="mb-3 text-sm">
                                    Realizado por Victoria Noci, Mohamed Malki y David Carrascal en la asignatura de SEDA.
                                </div>
                                <div><img src="https://raw.githubusercontent.com/davidcawork/Pi-Home/main/img/icons/uahGrande.png" / width="80%" style="max-width:100%;height: auto;display:block;margin:auto;padding-top: 10%;padding-bottom: 10%;">
                                </div>

                                <a href="https://github.com/davidcawork/Pi-Home" target="_blank" class="btn btn-primary btn-block" style="margin-top: 10px;">Repositorio Oficial</a>
                            </div>
                        </div>
                    </div>
                </nav>

                <div class="main">
                    <nav class="navbar navbar-expand navbar-light navbar-bg">
                        <a class="sidebar-toggle d-flex">
                            <i class="hamburger align-self-center"></i>
                        </a>
                        <form class="d-none d-sm-inline-block">
                            <div class="input-group input-group-navbar">
                                <input type="text" class="form-control" placeholder="Search…" aria-label="Search"/>
                                <button class="btn" type="button">
                                    <i class="align-middle" data-feather="search"></i>
                                </button>
                            </div>
                        </form>
                        <div class="navbar-collapse collapse">
                            <ul class="navbar-nav navbar-align">
                                <li class="nav-item dropdown d-sm-inline-block">
                                    <i class="align-middle" style="margin-bottom: 7px; margin-right: 2px;" data-feather="database"></i>