</div>
</div>
</div>

</div>
<div class="row  mb-2 mb-xl-3" style="margin-top: 1%;">
<div class="col-auto d-none d-sm-block">  
<h3>
    <strong>Umbral</strong>
    de temperatura</h3>
</div>
</div>
<div class="row">
<div class="col-md-6">
<div class="card">
    <div class="card-body">
        <h5 class="card-title mb-4">Alarma por temperatura
            <i class="align-middle mr-2" style="margin-bottom: 4px;margin-left: 4px;" data-feather="alert-triangle"></i>
        </h5>